apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-website-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    # Using master node as NFS server
    server: 172.31.15.198
    path: /mnt/shared-disk/website
