# AWS Services Pre-requisites Setup Guide
# This script helps you set up the required AWS services
# Run this BEFORE deploying the Kubernetes manifests

echo "============================================="
echo " AWS Services Setup for K8s HA Website"
echo "============================================="

# ─── 1. AWS EFS (Elastic File System) ───
echo ""
echo "📁 STEP 1: Create AWS EFS File System"
echo "────────────────────────────────────────"
echo ""
echo "  a) Create EFS via AWS CLI:"
echo "     aws efs create-file-system \\"
echo "       --creation-token k8s-ha-website-efs \\"
echo "       --performance-mode generalPurpose \\"
echo "       --throughput-mode bursting \\"
echo "       --encrypted \\"
echo "       --tags Key=Name,Value=k8s-ha-website-efs \\"
echo "       --region us-east-1"
echo ""
echo "  b) Create Mount Targets in each subnet where K8s nodes run:"
echo "     aws efs create-mount-target \\"
echo "       --file-system-id fs-XXXXXXXXX \\"
echo "       --subnet-id subnet-XXXXXXXX \\"
echo "       --security-groups sg-XXXXXXXX"
echo ""
echo "  c) Install EFS CSI Driver in your cluster:"
echo "     kubectl apply -k \"github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-2.0\""
echo ""
echo "  d) Update aws/efs-storageclass.yaml with your File System ID"
echo ""

# ─── 2. AWS RDS (MySQL) ───
echo "🗄️  STEP 2: Create AWS RDS MySQL Instance"
echo "────────────────────────────────────────"
echo ""
echo "  a) Create RDS MySQL instance via AWS CLI:"
echo "     aws rds create-db-instance \\"
echo "       --db-instance-identifier k8s-ha-website-db \\"
echo "       --db-instance-class db.t3.micro \\"
echo "       --engine mysql \\"
echo "       --engine-version 8.0 \\"
echo "       --master-username guestbook_user \\"
echo "       --master-user-password 'Guest@RDS2026!Secure' \\"
echo "       --allocated-storage 20 \\"
echo "       --db-name guestbook \\"
echo "       --vpc-security-group-ids sg-XXXXXXXX \\"
echo "       --db-subnet-group-name your-subnet-group \\"
echo "       --multi-az \\"
echo "       --storage-encrypted \\"
echo "       --backup-retention-period 7 \\"
echo "       --region us-east-1"
echo ""
echo "  b) IMPORTANT: Ensure the RDS Security Group allows inbound"
echo "     TCP 3306 from your K8s node Security Group."
echo ""
echo "  c) Once RDS is available, get the endpoint:"
echo "     aws rds describe-db-instances \\"
echo "       --db-instance-identifier k8s-ha-website-db \\"
echo "       --query 'DBInstances[0].Endpoint.Address' --output text"
echo ""
echo "  d) Base64 encode and update aws/rds-secret.yaml:"
echo "     echo -n 'your-rds-endpoint.us-east-1.rds.amazonaws.com' | base64"
echo ""

# ─── 3. AWS S3 ───
echo "📦 STEP 3: Create AWS S3 Bucket"
echo "────────────────────────────────────────"
echo ""
echo "  a) Create S3 bucket for static assets and backups:"
echo "     aws s3api create-bucket \\"
echo "       --bucket k8s-ha-website-assets \\"
echo "       --region us-east-1"
echo ""
echo "  b) Enable versioning:"
echo "     aws s3api put-bucket-versioning \\"
echo "       --bucket k8s-ha-website-assets \\"
echo "       --versioning-configuration Status=Enabled"
echo ""
echo "  c) Enable server-side encryption:"
echo "     aws s3api put-bucket-encryption \\"
echo "       --bucket k8s-ha-website-assets \\"
echo "       --server-side-encryption-configuration '{\"Rules\":[{\"ApplyServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}'"
echo ""
echo "  d) Create lifecycle policy for log rotation:"
echo "     aws s3api put-bucket-lifecycle-configuration \\"
echo "       --bucket k8s-ha-website-assets \\"
echo "       --lifecycle-configuration '{\"Rules\":[{\"ID\":\"log-cleanup\",\"Status\":\"Enabled\",\"Filter\":{\"Prefix\":\"app-logs/\"},\"Transitions\":[{\"Days\":30,\"StorageClass\":\"GLACIER\"}],\"Expiration\":{\"Days\":90}}]}'"
echo ""

# ─── 4. IAM Roles ───
echo "🔐 STEP 4: Configure IAM (IRSA or Node IAM Role)"
echo "────────────────────────────────────────"
echo ""
echo "  Your K8s nodes need IAM permissions for:"
echo "    - EFS: elasticfilesystem:ClientMount, elasticfilesystem:ClientWrite"
echo "    - S3:  s3:PutObject, s3:GetObject, s3:ListBucket"
echo "    - RDS: (accessed via network, no IAM policy needed if using password auth)"
echo ""
echo "  Option A: Node IAM Role (simpler)"
echo "    Attach policies to the IAM role assigned to your EC2 instances."
echo ""
echo "  Option B: IRSA (more secure, recommended for EKS)"
echo "    Create a Service Account with IAM role annotation."
echo ""

echo ""
echo "============================================="
echo " After completing the above steps, deploy:"
echo "============================================="
echo ""
echo "  # 1. Apply AWS resources"
echo "  kubectl apply -f aws/"
echo ""
echo "  # 2. Deploy backend"
echo "  kubectl apply -f backend/backend-deployment.yaml"
echo "  kubectl apply -f backend/backend-service.yaml"
echo ""
echo "  # 3. Deploy frontend"
echo "  kubectl apply -f deployment.yaml"
echo "  kubectl apply -f service.yaml"
echo "  kubectl apply -f ingress.yaml"
echo ""
