apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 172.31.15.198
    path: /mnt/shared-disk/mysql-data
